### ISSUE TITLE
大佬 我使用v2ray.sh和xray.sh时会报错怎么办

### ISSUE THREAD

**Issue by CHANGLERCN** [Miuzarte/hijk.sh#2]
v2ray.sh: line 8: syntax error near unexpected token `newline'
v2ray.sh: line 8: `<!DOCTYPE html>'
xray.sh: line 8: syntax error near unexpected token `newline'
xray.sh: line 8: `<!DOCTYPE html>'

**Comment by Miuzarte** [comment]
> 我自己只用过trojango，其他的报错我也没法解决，你用ubuntu/centos_install_v2ray那个试试吧

**Comment by CHANGLERCN** [comment]
centos_install_v2ray2.sh: line 8: syntax error near unexpected token `newline'
centos_install_v2ray2.sh: line 8: `<!DOCTYPE html>'
还是会报错 我google搜索说是换行符附近语法错误

**Comment by Miuzarte** [comment]
> centos_install_v2ray2.sh: line 8: syntax error near unexpected token `newline'
> centos_install_v2ray2.sh: line 8: `<!DOCTYPE html>'
> 还是会报错 我google搜索说是换行符附近语法错误

这第8行不就一个设置变量而已吗  怎么还能报错，文件下载方式是什么

**Comment by CHANGLERCN** [comment]
大佬对不起 给您添麻烦了 我应该点进源码的页面再复制链接的....我太小白了，对不起给您添麻烦了，现在已经好了

**Comment by CHANGLERCN** [comment]
我应该把链接弄成这个https://raw.githubusercontent.com/Miuzarte/hijk.sh/main/Fixed/xray.sh
而不是这个https://github.com/Miuzarte/hijk.sh/blob/main/Fixed/xray.sh
